### ISSUE TITLE
Configure cookie path

### ISSUE THREAD

**Issue by christianuhlcc** [Palmabit-IT/react-cookie-law#16]
Hi, we're using react-cookie-law and see the following behaviour: the consent cookie `rcl_consent_given ` is always set to the current path (default behaviour of the React-Cookies library you are using)

We have people landing and entering on all kinds of pages via search engine, e.g. `/foo/bar/baz`. Of course we have to display the cookie overlay right away. When the users consents, and then moves upwards in the directory hierarchy, they see the warning again (e,g. the cooke with the path `/foo/bar/baz` is not available on `/foo` anymore)

To solve this, one could set the path of `rcl_consent_given ` and the others to `/`, so that these cookies are available for the whole domain. This could either be done via a config option or by hardcoding it in cookies.js in the options of the cookie (see https://github.com/reactivestack/cookies/tree/master/packages/react-cookie#setname-value-options)

I would be happy to provide a PR for either solution, if you can give me a hint on what you prefer :-)

**Comment by b3nab** [comment]
I'm doing a small update to support this as I have the same kind of problem to solve for a project I'm building.

Someone of Palmabit (the repo maintainer) are interested in a PR and ?
Because I need it as soon as possible. :+1:
