### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by chriskaya** [Palmabit-IT/react-cookie-law#27]
Hi,

First of all, thank you for your work, it seems to be exactly what I need :)
I'm having an issue at startup:
```
./node_modules/@palmabit/react-cookie-law/dist/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: '.\node_modules\React\react'.
```
I'm using v0.6.1, on windows (git bash).

It seems to be caused by 2 `require('React')` in `dist/index.js` (works with `require('react')`). It might be related to this addition in `webpack.config.js` commit 4ce11ca3874c9ec5cc5ce9f235e68e542dbe5259:
```
  externals: {
    react: 'React',
  },
```

Could you have a look please? :)

Edit: confirmed on my side, I created a PR: #28

**Comment by asarzina** [comment]
Merged, thanks!

**Comment by chriskaya** [comment]
You're welcome :)
